version: "3.9"

services:
  web:
    build: .
    command: gunicorn conf.wsgi -b 0.0.0.0:8000
    ports:
      - 5432:5432
    environment:
      - "DEBUG=0"
      - "ENVIRONMENT=production"
    depends_on:
      - db
  db:
    image: postgres:13
    environment: 
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"