# Generated by Django 3.2.7 on 2021-09-25 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=40, null=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Default',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wth.city')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('IMP', 'imperial'), ('MET', 'metric')], default='MET', max_length=3)),
                ('cities', models.ManyToManyField(to='wth.City')),
                ('default', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='wth.default')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
